### ISSUE TITLE
Research related stuff

### ISSUE THREAD

**Issue by Apoch-zxv** [Apoch-zxv/roborob#5]
use #4 and #3 

http://www.lego.com/en-us/mindstorms/?domainredir=mindstorms.lego.com

http://www.gizmag.com/top-ten-high-tech-toys-for-kids/30173/

**Comment by anya-cartoon** [comment]
http://www.kano.me/kit
http://www.instructables.com/tag/type-id/category-technology/
https://www.youtube.com/user/GeekGurlDiaries

**Comment by Apoch-zxv** [comment]
![ida_code_parsing](https://cloud.githubusercontent.com/assets/10537861/6426142/63d41816-bf53-11e4-97b8-fce11c89d025.gif)

**Comment by Apoch-zxv** [comment]
https://developers.google.com/blockly/about/examples
